//
//  EditWorker.swift
//  CleanSwift
//
//  Created by Lukasz szyszkowski on 13.11.2016.
//  Copyright (c) 2016 Lukasz Szyszkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

typealias EditWorkerUpdateFinished = () -> ()
class EditWorker
{
  private let dbWorker = EditDBWorker()
  
  func update(text:String?, finished:EditWorkerUpdateFinished) {
    dbWorker.updateText(text).then {
     finished()
    }
  }
}
