//
//  EditConfigurator.swift
//  CleanSwift
//
//  Created by Lukasz szyszkowski on 13.11.2016.
//  Copyright (c) 2016 Lukasz Szyszkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension EditViewController: EditPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension EditInteractor: EditViewControllerOutput
{
}

extension EditPresenter: EditInteractorOutput
{
}

class EditConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: EditConfigurator
  {
    struct Static {
      static var instance: EditConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = EditConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: EditViewController)
  {
    let router = EditRouter()
    router.viewController = viewController
    
    let presenter = EditPresenter()
    presenter.output = viewController
    
    let interactor = EditInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
