//
//  EditRouter.swift
//  CleanSwift
//
//  Created by Lukasz szyszkowski on 13.11.2016.
//  Copyright (c) 2016 Lukasz Szyszkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol EditRouterInput
{
  func closeViewController()
}

class EditRouter: EditRouterInput
{
  weak var viewController: EditViewController!
  private var closeClosure:(()->())?

  func closeViewController() {
    viewController.dismissViewControllerAnimated(true, completion: nil)
    if let closure = closeClosure {
      closure()
    }
  }
  
  func close(closure:()->()) {
    closeClosure = closure
  }
  
  func passDataToNextScene(segue: UIStoryboardSegue)
  {
  }
}
