//
//  EditModels.swift
//  CleanSwift
//
//  Created by Lukasz szyszkowski on 13.11.2016.
//  Copyright (c) 2016 Lukasz Szyszkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Edit {
  // MARK: - UpdateTextField
  struct UpdateTextField {
    struct Request {
      let text:String
    }
    
    struct Response {
      let text:String
    }
    
    struct ViewModel {
      let text:String
    }
  }
  
  // MARK: - UpdateContainerView
  struct UpdateContainerView {
    struct ViewModel {
      let backgroundColor:String
      let cornerRadius:CGFloat
    }
  }
  
  // MARK: - UpdateSaveButton
  struct UpdateSaveButton {
    struct Response {
      let title:String
    }
    
    struct  ViewModel {
      let title:NSAttributedString
      let backgroundColor:String
      let cornerRadius:CGFloat
    }
  }
  
  // MARK: - SaveAction
  struct SaveAction {
    struct Request {
      let text:String?
    }
  }
}

