//
//  HomeViewController.swift
//  CleanSwift
//
//  Created by Lukasz szyszkowski on 13.11.2016.
//  Copyright (c) 2016 Lukasz Szyszkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol HomeViewControllerInput
{
  func updateTextLabel(model:Home.UpdateTextLabel.ViewModel)
  func updateChangeTextButton(model:Home.UpdateChangeTextButton.ViewModel)
  func showEditViewController(model:Home.EditText.ViewModel)
  func updateView(model:Home.UpdateView.ViewModel)
}

protocol HomeViewControllerOutput
{
  func changeTextButtonAction()
  func updateTextLabel()
  func updateChangeTextButton()
  func updateView()
}

class HomeViewController: UIViewController
{
  var output: HomeViewControllerOutput!
  var router: HomeRouter!

  @IBOutlet weak var textLabel: UILabel!
  @IBOutlet weak var changeTextButton: UIButton!
  override func awakeFromNib()
  {
    super.awakeFromNib()
    HomeConfigurator.sharedInstance.configure(self)
  }

  override func viewDidLoad()
  {
    super.viewDidLoad()
    output.updateView()
    output.updateTextLabel()
    output.updateChangeTextButton()
  }
  
  override func viewWillAppear(animated: Bool) {
    super.viewWillAppear(animated)
  }
}

// MARK: Inputs

extension HomeViewController:HomeViewControllerInput {
  func updateTextLabel(model: Home.UpdateTextLabel.ViewModel) {
    textLabel.attributedText = model.text
  }
  
  func showEditViewController(model: Home.EditText.ViewModel) {
    router.showEditViewController(model)
  }
  
  func updateChangeTextButton(model: Home.UpdateChangeTextButton.ViewModel) {
    changeTextButton.setAttributedTitle(model.title, forState: .Normal)
    changeTextButton.backgroundColor = Color(rawValue: model.backgroundColor)?.make
    changeTextButton.layer.cornerRadius = model.cornerRadius
  }
  
  func updateView(model: Home.UpdateView.ViewModel) {
    view.backgroundColor = Color(rawValue: model.backgroundColor)?.make
  }
}

// MARK: actions

extension HomeViewController {
  
  @IBAction func changeTextButtonDidTap(sender: AnyObject) {
    output.changeTextButtonAction()
  }
}