//
//  HomeRouter.swift
//  CleanSwift
//
//  Created by Lukasz szyszkowski on 13.11.2016.
//  Copyright (c) 2016 Lukasz Szyszkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol HomeRouterInput
{
  func showEditViewController(model:Home.EditText.ViewModel)
}

class HomeRouter: HomeRouterInput
{
  weak var viewController: HomeViewController!

  func showEditViewController(model: Home.EditText.ViewModel) {
    let editViewController = viewController.storyboard?.instantiateViewControllerWithIdentifier(EditViewController.storyboardIdentifier()) as! EditViewController
    editViewController.inputData {
      let request = Edit.UpdateTextField.Request(text: model.text)
      editViewController.output.updateTextField(request)
    }
    editViewController.router.close { [weak self] in
      self?.viewController.output.updateTextLabel()
    }
    viewController.presentViewController(editViewController, animated: true, completion: nil)
  }
  
  func passDataToNextScene(segue: UIStoryboardSegue)
  {
  }
}
