//
//  HomeModels.swift
//  CleanSwift
//
//  Created by Lukasz szyszkowski on 13.11.2016.
//  Copyright (c) 2016 Lukasz Szyszkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Home {
  //MARK: - UpdateView
  struct UpdateView {
    struct ViewModel {
      let backgroundColor:String
    }
  }
  
  //MARK: - ChangeText
  struct ChnageText {
    struct Request {
      let text:String
    }
  }
  
  //MARK: - UpdateChangeTextButton
  struct UpdateChangeTextButton {
    struct Response {
      let title:String
    }
    
    struct ViewModel {
      let title:NSAttributedString
      let backgroundColor:String
      let cornerRadius:CGFloat
    }
  }
  
  //MARK: - UpdateTextLabel
  struct UpdateTextLabel {
    struct Response {
      let text:String
    }
    
    struct ViewModel {
      let text:NSAttributedString
    }
  }
  
  //MARK: - EditText
  struct EditText {
    struct Response {
      let text:String
    }
    
    struct ViewModel {
      let text:String
    }
  }
}

