//
//  HomeConfigurator.swift
//  CleanSwift
//
//  Created by Lukasz szyszkowski on 13.11.2016.
//  Copyright (c) 2016 Lukasz Szyszkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension HomeViewController: HomePresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension HomeInteractor: HomeViewControllerOutput
{
}

extension HomePresenter: HomeInteractorOutput
{
}

class HomeConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: HomeConfigurator
  {
    struct Static {
      static var instance: HomeConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = HomeConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: HomeViewController)
  {
    let router = HomeRouter()
    router.viewController = viewController
    
    let presenter = HomePresenter()
    presenter.output = viewController
    
    let interactor = HomeInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
