//
//  HomeWorker.swift
//  CleanSwift
//
//  Created by Lukasz szyszkowski on 13.11.2016.
//  Copyright (c) 2016 Lukasz Szyszkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

typealias HomeWorkerUpdateFinished = (String) -> ()
class HomeWorker
{
  private let dbWorker = HomeDBWorker()
  
  func fetchText(finished:HomeWorkerUpdateFinished) {
    dbWorker.fetchText().then{ object -> Void in
      if let object = object {
        finished(object.text ?? "")
      } else {
        finished("")
      }
    }
  }
}

// MARK: helpers

extension HomeWorker {
  private func objectToResponse(object:RMText?) -> Home.UpdateTextLabel.Response {
    guard let object = object else {
      return Home.UpdateTextLabel.Response(text: "")
    }
    
    let response = Home.UpdateTextLabel.Response(text:object.text ?? "")
    return response
  }
}
